### ISSUE TITLE
Wakelock doesn't quit

### ISSUE THREAD

**Issue by anishbajpai014** [haruue/WADB#3]
When using the "keep screen on", the wakelock doesn't quit after wadb is disabled.

**Comment by PinkD** [comment]
fixed in d242b9b

**Comment by anishbajpai014** [comment]
I am still experiencing this issue in latest release 2.3.1 when using the app from its tile. While I'm unsure of the cause of the bug, checking for `!wakeLock.isHeld()` in https://github.com/haruue/WADB/blob/master/app/src/main/java/moe/haruue/wadb/util/ScreenKeeper.java#L22 fixes the issue for me.

**Comment by anishbajpai014** [comment]
Yup! Has been fixed. Glad to have been of help. :)
